name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Firebase config file
        run: |
          cat > assignment-3/firebase.config.js <<EOF
          export const FIREBASE_CONFIG = {
            apiKey: "${{ secrets.APIKEY }}",
            authDomain: "${{ secrets.AUTHDOMAIN }}",
            databaseURL: "${{ secrets.DATABASEURL }}",
            projectId: "${{ secrets.PROJECTID }}",
            storageBucket: "${{ secrets.STORAGEBUCKET }}",
            messagingSenderId: "${{ secrets.MESSAGINGSENDERID }}",
            appId: "${{ secrets.APPID }}"
          };
          EOF

      - name: Confirm Firebase config exists
        run: |
          ls -la
          test -f firebase.config.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: assignment-3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
